DROP TABLE IF EXISTS `useraccounts`;
CREATE TABLE `useraccounts` (
  `id` int(30) NOT NULL auto_increment,
  `userid` varchar(30) default NULL,
  `srcid` varchar(30) default NULL,
  `token` int(10) default NULL,
  `srcnode` varchar(10) default NULL,
  `usercode` varchar(30) default NULL,
  `mac` varchar(36) default NULL,
  `userpass` varchar(30) default NULL,
  `useremail1` varchar(64) default NULL,
  `useremail2` varchar(64) default NULL,
  `question` varchar(30) default NULL,
  `answer` varchar(30) default NULL,
  `fname` varchar(20) default NULL,
  `lname` varchar(20) default NULL,
  `usertype` varchar(10) default NULL,
  `integral` int(10) default NULL,
  `byear` smallint(3) default NULL,
  `bmonth` smallint(3) default NULL,
  `bday` smallint(3) default NULL,
  `gender` varchar(8) default NULL,
  `occup` varchar(30) default NULL,
  `orgn` varchar(64) default NULL,
  `title` varchar(32) default NULL,
  `cid` varchar(30) default NULL,
  `ctype` varchar(10) default NULL,
  `regphone` varchar(30) default NULL,
  `phone` varchar(30) default NULL,
  `address` varchar(128) default NULL,
  `location` varchar(32) default NULL,
  `action` varchar(128) default NULL,
  `stat` varchar(3) default '100',
  `open1` varchar(3) default '100',
  `open2` varchar(3) default '100',
  `check` varchar(3) default '100',
  `memo` varchar(128) default NULL,
  `srcip` varchar(64) default NULL,
  `sender` varchar(36) default NULL,
  `netid` varchar(36) default NULL,
  `progid` varchar(36) default NULL,
  `intid` varchar(30) default NULL,
  `updtime` datetime default NULL,
  `rectime` datetime default NULL,
  `danwei` varchar(60) default NULL,
  `zhiwu` varchar(36) default NULL,
  `shenfen` varchar(36) default NULL,
  PRIMARY KEY  (`id`),
  KEY `userid` (`userid`),
  KEY `phone` (`phone`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

